# Generated by Django 5.1.4 on 2025-04-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminformation',
            name='item_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
