# Generated by Django 5.1.4 on 2025-04-27 14:51

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import generic.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_catalog', models.CharField(max_length=255)),
                ('table_schema', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('table_type', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Information Schema',
                'verbose_name_plural': 'Information Schemas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('template', models.CharField(choices=[('dashboard-generic-grid', 'Dashboard Generic Grid'), ('default-home-page', 'Default Home Page'), ('dashboard-generic-configuration', 'Dashboard Generic Configuration')], default='dashboard-generic-grid', max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('entity', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=100)),
                ('user_identifier', models.CharField(max_length=100)),
                ('caches', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('hide', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Generic Base Model',
                'verbose_name_plural': 'Generic Base Models',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangePasswordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('confirm_password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Generic Base Model',
                'verbose_name_plural': 'Generic Base Models',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('entity_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Generic Base Model',
                'verbose_name_plural': 'Generic Base Models',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=50)),
                ('entity', models.CharField(max_length=255)),
                ('caches', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=50)),
                ('entity', models.CharField(max_length=255)),
                ('caches', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderFooterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=50)),
                ('entity', models.CharField(blank=True, max_length=255, null=True)),
                ('caches', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('layout', 'Layout')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MetaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('config_caches', models.BooleanField(default=True)),
                ('copyright_text', models.CharField(max_length=255)),
                ('login_logo', models.FileField(blank=True, null=True, upload_to=generic.models.upload_to_assets)),
                ('login_logo_width', models.IntegerField(default=100)),
                ('login_logo_height', models.IntegerField(default=100)),
                ('favicon', models.FileField(blank=True, null=True, upload_to=generic.models.upload_to_assets)),
                ('sidebar_icon', models.FileField(blank=True, null=True, upload_to=generic.models.upload_to_assets)),
                ('sidebar_icon_width', models.IntegerField(default=100)),
                ('sidebar_icon_height', models.IntegerField(default=100)),
                ('default_auth', models.CharField(max_length=50)),
                ('banner', models.FileField(blank=True, null=True, upload_to=generic.models.upload_to_assets)),
                ('banner_width', models.IntegerField(default=100)),
                ('banner_height', models.IntegerField(default=100)),
                ('is_banner_fulll_screen', models.BooleanField(default=False)),
                ('banner_image_fill_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Generic Base Model',
                'verbose_name_plural': 'Generic Base Models',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to=generic.models.upload_to_assets)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_title_hide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_groups', to='generic.grouping')),
            ],
            options={
                'verbose_name': 'Generic Base Model',
                'verbose_name_plural': 'Generic Base Models',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('Group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='generic.grouping')),
            ],
        ),
        migrations.CreateModel(
            name='EntityPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('entity', models.CharField(max_length=255)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=True)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_permissions', to='generic.grouping')),
            ],
            options={
                'verbose_name': 'Generic Base Model',
                'verbose_name_plural': 'Generic Base Models',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupingEntityPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('entity_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=True)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='generic.grouping')),
            ],
            options={
                'verbose_name': 'Generic Base Model',
                'verbose_name_plural': 'Generic Base Models',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LCNCManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(default=generic.models.LCNCManagement.get_default_extra)),
                ('footer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lcnc_footer', to='generic.footerconfiguration')),
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lcnc_header', to='generic.headerconfiguration')),
                ('meta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lcnc_meta', to='generic.metaconfiguration')),
            ],
            options={
                'verbose_name': 'Generic Base Model',
                'verbose_name_plural': 'Generic Base Models',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='metaconfiguration',
            name='sidebar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_sidebar', to='generic.sidebar'),
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(help_text='Optional role of the user in this groups', max_length=255, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_users', to='generic.grouping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
    ]
