# Generated by Django 5.1.4 on 2025-04-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, default=dict, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('form_template', models.CharField(max_length=255)),
                ('entity', models.CharField(max_length=255)),
                ('width', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Generic Base Model',
                'verbose_name_plural': 'Generic Base Models',
                'abstract': False,
            },
        ),
    ]
